config/routes.rb
Rails.application.routes.draw do
  get '/simulations/:id', to: 'simulations#success', as: 'success'
  root "simulations#index" 
  resources :simulations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/simulation.rb
class Simulation < ApplicationRecord
  validates :nome, :nomeEmpresa, :faturamentoMensal, :prazoTitulo, :email, :valorTitulo, :presence => true
  validates :prazoTitulo, :numericality => { :greater_than_or_equal_to => 10 }
  validates :valorTitulo, :numericality => { :greater_than_or_equal_to => 500 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/simulations_controller.rb
class SimulationsController < ApplicationController
  before_action :set_simulation, only: [:show, :edit, :update, :destroy]

  def index
    @simulation = Simulation.new
  end

  def show

  end

  def edit
  end

  def success
    @simulation = Simulation.find(params[:id])
    @simulation.valorTaxa = (@simulation.prazoTitulo / 10).round * 1.65
    @simulation.valorReceber = (@simulation.valorTitulo - (@simulation.valorTitulo * (@simulation.valorTaxa/100)))

    #ToDo: Implementação de rotina para varia a taxa, eg. acima de 100k/mês é 1.5% e abaixo de 50k/mês é 1.8%);
  end

  def update
  end

  def create
    @simulation = Simulation.new(simulation_params)

    if @simulation.save
        redirect_to success_path(@simulation.id)
      else
      render "index"
    end
  end


  def simulation_params
    params.require(:simulation).permit(:nome, :email, :nomeEmpresa, :faturamentoMensal, :valorTitulo, :prazoTitulo, :valorTaxa, :valorReceber)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simulations_helper.rb
module SimulationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalculoTaxa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/simulations/_form.html.erb
<%= form_with(model: simulation, local: true) do |form| %>
  <% if simulation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(simulation.errors.count, "error") %> prohibited this simulation from being saved:</h2>

      <ul>
      <% simulation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :nomeEmpresa %>
    <%= form.text_field :nomeEmpresa %>
  </div>

  <div class="field">
    <%= form.label :faturamentoMensal %>
    <%= form.text_field :faturamentoMensal %>
  </div>

  <div class="field">
    <%= form.label :valorTitulo %>
    <%= form.text_field :valorTitulo %>
  </div>

  <div class="field">
    <%= form.label :prazoTitulo %>
    <%= form.text_field :prazoTitulo %>
  </div>

  <div class="field">
    <%= form.label :valorTaxa %>
    <%= form.text_field :valorTaxa %>
  </div>

  <div class="field">
    <%= form.label :valorReceber %>
    <%= form.text_field :valorReceber %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/simulations/index.html.erb
<h1>Simulador de Taxa de Factoring</h1>

<%= form_for @simulation do |form| %>

<% if @simulation.errors.any? %>
<h2>Errors:</h2>
<ul>
  <% @simulation.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<p>
  <%= form.label "Seu nome"  %>
  <%= form.text_field :nome  %>
</p>
<p>
  <%= form.label "Email" %>
  <%= form.text_area :email  %>
</p>
<p>
  <%= form.label "Empresa" %>
  <%= form.text_area :nomeEmpresa  %>
</p>
<p>
  <%= form.label "Faturamento Mensal"  %>
  <%= form.text_area :faturamentoMensal  %>
</p>
<p>
  <%= form.label "Valor do Título"  %>
  <%= form.text_area :valorTitulo  %>
</p>
<p>
  <%= form.label "Prazo do Título (dias)"  %>
  <%= form.text_area :prazoTitulo  %>
</p>
<p>
  <%= form.submit "Simular" %>
</p>
<% end %>

app/views/simulations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valor da taxa:</strong>
  <%= @simulation.valorTaxa %>
</p>

<p>
  <strong>Valor a receber:</strong>
  <%= @simulation.valorReceber %>
</p>

<%= link_to 'Simular novamente', simulations_path %>

app/views/simulations/success.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valor da taxa:</strong>
   <%= @simulation.valorTaxa %>%
</p>

<p>
  <strong>Valor a receber:</strong>
  R$ <%= @simulation.valorReceber %>
</p>

<%= link_to 'Simular novamente', simulations_path %>